-- MySQL Script generated by MySQL Workbench
-- 06/08/16 16:35:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nicewall
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nicewall` ;

-- -----------------------------------------------------
-- Schema nicewall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nicewall` DEFAULT CHARACTER SET utf8 ;
USE `nicewall` ;

-- -----------------------------------------------------
-- Table `nicewall`.`Perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`Perfil` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `tipoPerfil` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Perfil_idPerfil`),
  INDEX `fk_Usuario_Perfil_idx` (`Perfil_idPerfil` ASC),
  CONSTRAINT `fk_Usuario_Perfil`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `nicewall`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`Direccion` (
  `idDireccion` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  `Perfil_idPerfil` INT NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Perfil_idPerfil`, `Direccion_idDireccion`),
  INDEX `fk_Cliente_Perfil1_idx` (`Perfil_idPerfil` ASC),
  INDEX `fk_Cliente_Direccion1_idx` (`Direccion_idDireccion` ASC),
  CONSTRAINT `fk_Cliente_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `nicewall`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `nicewall`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`Producto` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`Producto` (
  `idProducto` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`SubProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`SubProducto` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`SubProducto` (
  `idSubProducto` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `stock` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idSubProducto`, `Producto_idProducto`),
  INDEX `fk_SubProducto_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_SubProducto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `nicewall`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`venta` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`venta` (
  `idventa` INT NOT NULL,
  `fechaVenta` DATETIME NOT NULL,
  `ventacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idventa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`Cliente_has_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`Cliente_has_venta` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`Cliente_has_venta` (
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Perfil_idPerfil` INT NOT NULL,
  `Cliente_Direccion_idDireccion` INT NOT NULL,
  `venta_idventa` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Cliente_Perfil_idPerfil`, `Cliente_Direccion_idDireccion`, `venta_idventa`),
  INDEX `fk_Cliente_has_venta_venta1_idx` (`venta_idventa` ASC),
  INDEX `fk_Cliente_has_venta_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Perfil_idPerfil` ASC, `Cliente_Direccion_idDireccion` ASC),
  CONSTRAINT `fk_Cliente_has_venta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Perfil_idPerfil` , `Cliente_Direccion_idDireccion`)
    REFERENCES `nicewall`.`Cliente` (`idCliente` , `Perfil_idPerfil` , `Direccion_idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_venta_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `nicewall`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nicewall`.`venta_has_Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nicewall`.`venta_has_Producto` ;

CREATE TABLE IF NOT EXISTS `nicewall`.`venta_has_Producto` (
  `venta_idventa` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`venta_idventa`, `Producto_idProducto`),
  INDEX `fk_venta_has_Producto_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_venta_has_Producto_venta1_idx` (`venta_idventa` ASC),
  CONSTRAINT `fk_venta_has_Producto_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `nicewall`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `nicewall`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
